### ISSUE TITLE
can't pass test EventRepository.find

### ISSUE THREAD

**Issue by terassyi** [spectrex02/event-app#7]
test result:

head of empty list
java.util.NoSuchElementException: head of empty list

**Comment by shomatan** [comment]
You should use .headOption instead of .head

**Comment by terassyi** [comment]
resolved: 

val votingSeq: Seq[(LocalDateTime, Vote)] = sql"select * from vote where id = ${id}".map{ rs =>
      (DateFormatter.string2date(rs.string("voting_date")),Vote(rs.get("participant_name"), VotingValue.from(rs.int("voting_status"))))
    }.list().apply()

    val a: Map[LocalDateTime, Seq[(LocalDateTime, Vote)]] = votingSeq.groupBy { case (d: LocalDateTime, v: Vote) => d }
    val aa: Map[LocalDateTime, Seq[Vote]] = a.map { case (d: LocalDateTime, s: Seq[(LocalDateTime, Vote)]) => d -> s.map { case (date: LocalDateTime, vote: Vote) => vote}.toSeq }
    val actualCandidateDates: CandidateDates = CandidateDates(aa.map { case (date: LocalDateTime, votes: Seq[Vote]) => Candidate(date, votes)}.toSeq)
